language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
    - bower_components
env:
  global:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/bin/
    - HUGO_VERSION=0.14
before_install:
  - ./scripts/install_hugo.sh
script:
  - npm start

deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: source
