language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
    - bower_components
env:
  global:
    - HUGO_VERSION=0.14
before_install:
  - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux_amd64.tar.gz
  - tar xvzf hugo_${HUGO_VERSION}_linux_amd64.tar.gz
  - mkdir $TRAVIS_BUILD_DIR/bin
  - mv hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 $TRAVIS_BUILD_DIR/bin/hugo
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin/
  - rm -rf hugo_${HUGO_VERSION}_linux_amd64*
script:
  - npm start

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: source
